# Generated by Django 5.1.1 on 2024-09-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_contact_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='messege',
            new_name='message',
        ),
    ]
